### ISSUE TITLE
Dependency guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by sdiama** [hpatoio/bitly-api#16]
guzzle/guzzle is abandoned and composer returns annoying messsage. Is should be used guzzlehttp/guzzle instead.

**Comment by hpatoio** [comment]
Which version are you using ? Try with latest master.
Can you please send me your `composer.json` ?

**Comment by kissifrot** [comment]
Could you maybe do a point-release ? This would also enable HpatoioBitlyBundle to use it, thus eliminating the warning

**Comment by audvin** [comment]
Would be great if we could change this to `guzzlehttp/guzzle": "~6.0",` and update whatever needs to be updated...

https://github.com/hpatoio/bitly-api/blob/master/composer.json#L15

**Comment by hpatoio** [comment]
I tagged a new release. Please let me know if things are better now.

**Comment by casenjo** [comment]
@hpatoio I just ran `composer require hpatoio/bitly-api` but still got the message.
My composer.json reads `"hpatoio/bitly-api": "^2.0"`, should I change it to something else so that it uses the newer guzzlehttp/guzzle package?
