### ISSUE TITLE
update guzzle

### ISSUE THREAD

**Issue by reinder83** [hpatoio/bitly-api#19]
I'm trying to install this package together with aws/aws-php-sdk but this is conflicting with the version of guzzlehttp/guzzle.

For now I set bitly-api to use version 2.0.2 so installs the old version of guzzle/guzzle, but this given me the following warning:
"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead."

The current guzzle requirement for aws-php-sdk is:
 "guzzlehttp/guzzle": "^5.3.1|^6.2.1"

**Comment by hpatoio** [comment]
Guzzle dependency was update in `2.0.3` - https://github.com/hpatoio/bitly-api/releases/tag/2.0.3
As you can see this bundle now it depends on `guzzlehttp/guzzle` - https://github.com/hpatoio/bitly-api/blob/master/composer.json#L15

**Comment by reinder83** [comment]
yes it depends on ~3.0, aws-php-sdk needs ^5.3.1 or ^6.2.1

**Comment by hpatoio** [comment]
@teolaz you are free to open a PR and fix the issue.

**Comment by phplicengine** [comment]
Our lib is for Bitly Api v4.
https://github.com/phplicengine/bitly
