### ISSUE TITLE
Add OAuth2 

### ISSUE THREAD

**Issue by hpatoio** [hpatoio/bitly-api#5]
Integrate Guzzle OAuth2 plugin. WIP here https://github.com/guzzle/oauth-subscriber/pull/3

**Comment by acrozes** [comment]
Now to use bitly we need to use oauth
Are you going to update this lib (and the symfony bundle) ?

**Comment by hpatoio** [comment]
@acrozes what do you mean with "Now to use bitly we need to use oauth" ? Oauth it has always been required if you wanted to create per user shortlink. Yes sure, I'm planning to add oauth but you can use the library anyway.

**Comment by acrozes** [comment]
Yes you right, the new bitly interface hide the deprecated token in favor the oauth but by the dev interface we can find the way to define a simple token to use this lib.

**Comment by phplicengine** [comment]
Our lib is for Bitly Api v4.
https://github.com/phplicengine/bitly
